import { vi } from "vitest";
import { ChatContextType } from "../contexts/ChatContext";
import { SettingsContextType } from "../contexts/SettingsContext";

export const getMockChatContext = (): ChatContextType => ({
  chatHistory: [],
  setChatHistory: vi.fn(),
  tree: [],
  toggleCollapse: vi.fn(),
  messagesContainerRef: { current: null },
  scrollToBottom: vi.fn(),
  clearChatHistory: vi.fn(),
});

export const getMockSettingsContext = (): SettingsContextType => ({
  openFiles: [],
  setOpenFiles: vi.fn(),
  systemPrompts: [],
  setSystemPrompts: vi.fn(),
  userPrompts: [],
  setUserPrompts: vi.fn(),
  availableTools: [],
  setAvailableTools: vi.fn(),
  availableShells: [],
  setAvailableShells: vi.fn(),
  enabledTools: [],
  setEnabledTools: vi.fn(),
  providerSettingsList: [],
  setProviderSettingsList: vi.fn(),
  currentProviderSetting: undefined,
  setCurrentProviderSetting: vi.fn(),
  availableVendors: [],
  setAvailableVendors: vi.fn(),
  systemPromptsPopupVisible: false,
  setSystemPromptsPopupVisible: vi.fn(),
  userPromptsPopupVisible: false,
  setUserPromptsPopupVisible: vi.fn(),
  toolPopupVisible: false,
  setToolPopupVisible: vi.fn(),
  providerSettingsPopupVisible: false,
  setProviderSettingsPopupVisible: vi.fn(),
  privacySettingsPopupVisible: false,
  setPrivacySettingsPopupVisible: vi.fn(),
  editingProviderName: null,
  setEditingProviderName: vi.fn(),
  editingPrivacyPairSearch: null,
  setEditingPrivacyPairSearch: vi.fn(),
  currentSystemPrompt: "",
  setCurrentSystemPrompt: vi.fn(),
  currentUserPrompt: "",
  setCurrentUserPrompt: vi.fn(),
  currentRunCommand: "",
  setCurrentRunCommand: vi.fn(),
  currentSelectedShell: "",
  setCurrentSelectedShell: vi.fn(),
  autoRemoveComments: true,
  setAutoRemoveComments: vi.fn(),
  autoFormat: true,
  setAutoFormat: vi.fn(),
  autoFixErrors: true,
  setAutoFixErrors: vi.fn(),
  autoGenerateCommit: false,
  setAutoGenerateCommit: vi.fn(),
  useConventionalCommits: false,
  setUseConventionalCommits: vi.fn(),
  includeCodebaseSummary: false,
  setIncludeCodebaseSummary: vi.fn(),
  privacySettings: [],
  setPrivacySettings: vi.fn(),
  isPrivacyMaskingEnabled: false,
  setIsPrivacyMaskingEnabled: vi.fn(),
  planState: {
    status: "idle",
    currentStepIndex: -1,
    plan: null,
    error: null,
    filePaths: [],
    providerSetting: null,
    autoRemoveComments: true,
    autoFormat: true,
    autoFixErrors: true,
    stepCollapsedStates: [],
    tabId: "test-tab-id",
  },
  setPlanState: vi.fn(),
  providerForm: {
    name: "",
    vendor: "",
    apiKey: "",
    baseURL: "",
    model: "",
    provider: "",
    maxTokens: "",
    temperature: "",
  },
  setProviderForm: vi.fn(),
  privacyForm: { search: "", replace: "" },
  setPrivacyForm: vi.fn(),
  sendSettingsUpdate: vi.fn(),
  updateSystemPrompt: vi.fn(),
  updateUserPrompt: vi.fn(),
  updateRunCommand: vi.fn(),
  updateSelectedShell: vi.fn(),
  saveSystemPrompt: vi.fn(),
  saveUserPrompt: vi.fn(),
  loadSystemPrompt: vi.fn(),
  loadUserPrompt: vi.fn(),
  deleteSystemPrompt: vi.fn(),
  deleteUserPrompt: vi.fn(),
  removeFile: vi.fn(),
  removeTool: vi.fn(),
  userInputRef: { current: null },
  systemPromptRef: { current: null },
  runCommandInputRef: { current: null },
  shellSelectorRef: { current: null },
  postMessage: vi.fn(),
  tabId: "test-tab-id",
  toggleToolPopup: vi.fn(),
  toggleProviderSettingsPopup: vi.fn(),
  togglePrivacySettingsPopup: vi.fn(),
});
